### ISSUE TITLE
damovworkloadspart2.git && damovworkloadspart3.git can't be Decompressing

### ISSUE THREAD

**Issue by john1shanghai** [CMU-SAFARI/DAMOV#1]
Hi sir
download damovworkloadspart2.git && damovworkloadspart3.git sucessfully ,error "tar: This does not look like a tar archive"  during decompressing ,however,  damovworkloadspart1.git can be decompressing without error, could you please check the workloads_part2.tar.lrz && workloads_part3.tar.lrz is normal or not? thanks
Montage Technology (Shanghai) Co.,Ltd.
7F,Technology Bldg.,900 Yi Shan Rd, Shanghai 200233, China
Tel: 021-54679038 Ext: 18263
Fax: 021-54263132
E-mail: tao.fang@montage-tech.com
澜起科技（上海）股份有限公司
上海市宜山路900号科技大楼A栋7楼（200233）
Phone: +86-18601425768

**Comment by john1shanghai** [comment]
issue has been fixed by installing lrzlib2-dev;lrzlib4-dev;lrzlib02-dev

**Comment by abhishekk06** [comment]
Hi,

Are things working fine? For some reason get_workloads.sh is super slow. Stuck in workloadpart1(unpacking 50%) for the last 30 mins.
