### ISSUE TITLE
gm create failed shmget: Cannot allocate memory

### ISSUE THREAD

**Issue by cloudsreal** [CMU-SAFARI/DAMOV#14]
Hi, sir.
When I try to Running the Application from DAMOV with the command "./build/opt/zsim config_files/host_ooo/no_prefetch/stream/4/Add_Add.cfg" on my Linux, I meet the error message "gm create failed shmget: Cannot allocate memory". 
How can I resolve the this issue?

**Comment by GowthamD909** [comment]
Hi cloudsreal , did u resolve the issue ?
I'm facing the same issue

**Comment by geraldofojunior** [comment]
You ran out of memory -- you can try reducing the gm space in the configuration file.
