### ISSUE TITLE
Request for information regarding building and executing DAMOV on dockers

### ISSUE THREAD

**Issue by ssatyendras** [CMU-SAFARI/DAMOV#15]
Hello,
I am trying to build and execute the tool on a shared server. Is there any information regarding the compatibility of DAMOV with dockers?
 Thanks & Regards,
Siva

**Comment by gearaldojunior** [comment]
Hi Siva,

We have prepared a Docker container with built DAMOV-SIM: docker pull gfojunior/damov:latest

Please, check the README for further information. 

Thanks.
Regards.

**Comment by ssatyendras** [comment]
Thank you.
