### ISSUE TITLE
sh ./scripts/compile.sh failing

### ISSUE THREAD

**Issue by GowthamD909** [CMU-SAFARI/DAMOV#17]
The issue is resolved

**Comment by Lo-kesh4** [comment]
Hey Gowtham in your error there you can see the note saying 
note : 'uint64_t is defined in header.........
So, just go to the regarding path and add the header file (include <cstdint>in between 7 and 8th line. That error will be solved

**Comment by GowthamD909** [comment]
Lokesh I'm facing scons error as well

**Comment by GowthamD909** [comment]
> Hey Gowtham in your error there you can see the note saying note : 'uint64_t is defined in header......... So, just go to the regarding path and add the header file (include in between 7 and 8th line. That error will be solved

Ya lokesh ,but I'm facing makefile error as well as scons errors,same errors u are facing
