### ISSUE TITLE
Ramulator installation error

### ISSUE THREAD

**Issue by Lo-kesh4** [CMU-SAFARI/DAMOV#19]
~/DAMOV/simulator/ramulator$ make -j
g++ -DRAMULATOR -Wall -std=c++11 -w -O3   -o ramulator ALDRAM.o Cache.o Config.o Controller.o DDR3.o DDR4.o DSARP.o GDDR5.o HBM.o HMC.o LogicLayer.o LPDDR3.o LPDDR4.o MemoryFactory.o Packet.o Processor.o RamulatorWrapper.o Refresh.o SALP.o StatType.o TLDRAM.o WideIO2.o WideIO.o 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:34: ramulator] Error 1

How to solve this error....

**Comment by geraldofojunior** [comment]
I am not sure what the issue is with such a short description. Please try cleaning and building, ensuring you successfully ran the setup script. If it does not work, I suggest using DAMOV's docker container.
