### ISSUE TITLE
excute the sh ./script/compile fail 

### ISSUE THREAD

**Issue by john1shanghai** [CMU-SAFARI/DAMOV#2]
Hi sir

when i execute { sh ./script/compile.sh },there are two errors show after compile 
make[1]: *** [Makefile:370: libconfig.info] Error 127
make[1]: Leaving directory '/home/DAMOV-main/simulator/libconfig/doc'
make: *** [Makefile:445: install-recursive] Error 1
i have excuted it under root with ubuntu 20.4  and try to install relates application from the website ,still fail , i noticed that the ubuntu 20.4 not including in the os support list , could you please give some advices?

Montage Technology (Shanghai) Co.,Ltd.
7F,Technology Bldg.,900 Yi Shan Rd, Shanghai 200233, China
Tel: 021-54679038 Ext: 18263
Fax: 021-54263132
E-mail: tao.fang@montage-tech.com
澜起科技（上海）股份有限公司
上海市宜山路900号科技大楼A栋7楼（200233）
Phone: +86-18601425768

**Comment by gearaldojunior** [comment]
Hi,

I tried to reproduce the error using an Ubuntu 18.04 machine but the compile.sh script worked well for me.

Apparently, the issue you are facing is related to installing libconfig. Can you try to install it using other methods (you can check it [here](https://linux-packages.com/ubuntu-focal-fossa/package/libconfig-dev)). Note that, if this works, you need to modify the compiler.sh script to skip the installation of libconfig. 

Thanks.
