### ISSUE TITLE
 gm_create failed shmget: Cannot allocate memory

### ISSUE THREAD

**Issue by Shalett** [CMU-SAFARI/DAMOV#20]
./build/opt/zsim config_files/host_ooo/no_prefetch/stream/4/Add_Add.cfg

gm_create failed shmget: Cannot allocate memory
 How do I resolve this error

**Comment by Shalett** [comment]
issue is resolved

**Comment by satanu01** [comment]
> issue is resolved

Can you please help me that how you solve this problem?
