### ISSUE TITLE
killing simulation

### ISSUE THREAD

**Issue by Lo-kesh4** [CMU-SAFARI/DAMOV#21]
[H] Starting zsim, built Saturday 15 July 2023 07:45:07 PM IST (rev no git repo)
[H] Creating global segment, 8192 MBs
[H] Global segment shmid = 32774
[H] Deadlock detection OFF
[S 0] Started instance
[S 0] Started RR scheduler, quantum=10000 phases
Cache sys.caches.l3. has 8388608 (8 MB 
[S 0] l3-0b0: mshrs 16 domain 0
[S 0] l3-0b1: mshrs 16 domain 0
[S 0] l3-0b2: mshrs 16 domain 0
[S 0] l3-0b3: mshrs 16 domain 0
[S 0] l3-0b4: mshrs 16 domain 0
[S 0] l3-0b5: mshrs 16 domain 0
[S 0] l3-0b6: mshrs 16 domain 0
[S 0] l3-0b7: mshrs 16 domain 0
[S 0] l3-0b8: mshrs 16 domain 0
[S 0] l3-0b9: mshrs 16 domain 0
[S 0] l3-0b10: mshrs 16 domain 0
[S 0] l3-0b11: mshrs 16 domain 0
[S 0] l3-0b12: mshrs 16 domain 0
[S 0] l3-0b13: mshrs 16 domain 0
[S 0] l3-0b14: mshrs 16 domain 0
[S 0] l3-0b15: mshrs 16 domain 0
Cache sys.caches.l2. has 262144 (0 MB 
Cache sys.caches.l1i. has 32768 (0 MB 
Cache sys.caches.l1d. has 32768 (0 MB 
/home/loki/Desktop/DAMOV/simulator zsim_stats/host_ooo/no_prefetch/4/stream_Add_Add
total_vault_number: 32
Request type = 0 is a read 
Request type = 1 is a write 
Application name at get_application_name: /home/loki/Desktop/DAMOV/simulator/zsim_stats/host_ooo/no_prefetch/4/stream_Add_Add
Channel widht: 64
[RAMULATOR] Initialized Ramulator
[S 0] [RAMULATOR] Mem frequency 1250.000000
[S 0] [RAMILATOR] CPU/Mem frequency ratio 2
/home/loki/Desktop/DAMOV/simulator/zsim_stats/host_ooo/no_prefetch/4/stream_Add_Add.ramulator.stats <- 
[S 0] Hierarchy: [ l1i-0 l1d-0 ] -> l2-0
[S 0] Hierarchy: [ l1i-1 l1d-1 ] -> l2-1
[S 0] Hierarchy: [ l1i-2 l1d-2 ] -> l2-2
[S 0] Hierarchy: [ l1i-3 l1d-3 ] -> l2-3
[S 0] Hierarchy: [ l2-0 l2-1 l2-2 l2-3 ] -> l3-0b0..l3-0b15
[S 0] Initialized system
[S 0] Initialization complete
/home/loki/Desktop/DAMOV/simulator/zsim_stats/host_ooo/no_prefetch/4/stream_Add_Add
[S 0] Started process, PID 18325
[S 0] procMask: 0x0
[S 0] vDSO info initialized
[H] Attached to global heap
[S 0] Started scheduler watchdog thread
[S 0] Started contention simulation thread 0
[S 0] FF control Thread TID 18330
A: Source/pin/vm_ia32_l/emu_ia32_linux.cpp: ExecuteSysArchPrct1: 664: Unknown sub-function for SYS_arch_prctl

################################################################################
################################################################################
addr2line -C -f -e "/home/loki/Desktop/DAMOV/simulator/pin/intel64/bin/pinbin" 0x3041c07f9 0x3041c15ce 0x3041c18a0 0x3043c2122 0x3043c48e6 0x30432df2b 0x304317874 0x3042f95db 0x304380868
LEVEL_BASE::MESSAGE_TYPE::DumpTrace()
??:?
LEVEL_BASE::MESSAGE_TYPE::MessageInternal(std::string const&, bool, PIN_ERRTYPE, __va_list_tag*, int)
??:?
LEVEL_BASE::MESSAGE_TYPE::MessageNoReturn(std::string const&, bool, PIN_ERRTYPE, int, ...)
??:?
LEVEL_VM::EMULATOR::ExecuteSysArchPrct1()
??:?
LEVEL_VM::EMULATOR::ExecuteSysCall(LEVEL_VM::INS_EMU_INFO const*)
??:?
LEVEL_VM::EMULATOR_IA32::EmulateOneInstruction(LEVEL_VM::INS_EMU_INFO const*)
??:?
LEVEL_VM::VMSVC_Emu(LEVEL_VM::SCT_ATTRIBUTES const*, LEVEL_VM::PCTXT*, LEVEL_VM::VMSVC_EMU_ARGS const*)
??:?
LEVEL_VM::VM::Dispatch(LEVEL_VM::VMSVC_ARGS const*, LEVEL_VM::PCTXT*)
??:?
VmLeave
??:?
Detach Service Count: 221
Pin 2.14
Copyright (c) 2003-2015, Intel Corporation. All rights reserved.
@CHARM-VERSION: $Rev: 71293 $
@CHARM-BUILDER: BUILDER
@CHARM-COMPILER: gcc 4.4.7
@CHARM-TARGET: ia32e
@CHARM-CFLAGS:  __OPTIMIZE__=1  __NO_INLINE__=__NO_INLINE__
[H] Child 18325 done
[H] Panic on build/opt/zsim_harness.cpp:123: Child 18325 (idx 0) exit was anomalous, killing simulation

**Comment by qcjiang** [comment]
I fixed this issue in my respository, see https://github.com/qcjiang/DAMOV

**Comment by Zst0514** [comment]
> I fixed this issue in my respository, see https://github.com/qcjiang/DAMOV

Hello,I've encountered the same issue as you described in this issue. Could you please share how you resolved it? Thank you!

**Comment by qcjiang** [comment]
Hi, could you tell me who you are?
        
    Basically you can just use the repository I provided at https://github.com/qcjiang/DAMOV. It works well with Ubuntu 18/20. If it doesn't work, I highly recommend you to use DAMOV's docker environment: gfojunior/damov:latest.
        
            
        
    
                 
            
                font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }Best regards,Qingcai
            
        
             
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        1/6/2024 08:38
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Qingcai ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [CMU-SAFARI/DAMOV] killing simulation (Issue #21)
        
      
    
  


I fixed this issue in my respository, see https://github.com/qcjiang/DAMOV

Hello,I've encountered the same issue as you described in this issue. Could you please share how you resolved it? Thank you!

**Comment by geraldofojunior** [comment]
> Hi, could you tell me who you are? Basically you can just use the repository I provided at https://github.com/qcjiang/DAMOV. It works well with Ubuntu 18/20. If it doesn't work, I highly recommend you to use DAMOV's docker environment: gfojunior/damov:latest. font{ line-height: 1.6; }font{ line-height: 1.6; }font{ line-height: 1.6; }font{ line-height: 1.6; }font{ line-height: 1.6; }font{ line-height: 1.6; }font{ line-height: 1.6; }font{ line-height: 1.6; }Best regards,Qingcai
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 1/6/2024 08:38 To ***@***.***> Cc Qingcai ***@***.***> , ***@***.***> Subject Re: [CMU-SAFARI/DAMOV] killing simulation (Issue #21) I fixed this issue in my respository, see https://github.com/qcjiang/DAMOV Hello,I've encountered the same issue as you described in this issue. Could you please share how you resolved it? Thank you! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by apoorvaaaa5** [comment]
Hey, I am getting the same issue, could you tell me how to resolve it??
