### ISSUE TITLE
automation in running simulation

### ISSUE THREAD

**Issue by apoorvaaaa5** [CMU-SAFARI/DAMOV#23]
hey i wanted to know is there any automation like bash script so that i can simulate for multiple features at the same time like host ooo,pim ooo for multiple cores. any bash script for automating simulation would be helpful

**Comment by geraldofojunior** [comment]
We do not provide any automation script. You can create a python script and loop over the configuration files:

import sys 

templates = ["config1.cfg", "config2.cfg", "config3.cfg"]

for t in templates:
    os.system ("./build/opt.zsim "+ t)

**Comment by apoorvaaaa5** [comment]
Ok thank you i will try doing that!!
