### ISSUE TITLE
trace generator for hybrid memory cube 

### ISSUE THREAD

**Issue by apoorvaaaa5** [CMU-SAFARI/DAMOV#24]
Hey i wanted to know if there is trace generator for Hybrid memory cube(HMC) in DAMOV??

**Comment by geraldofojunior** [comment]
There is no trace generator in DAMOV since DAMOV directly executes the binary of the applications.

You can check ramulator-PIM for trace generation: https://github.com/CMU-SAFARI/ramulator-pim

Thanks.
Regards.

**Comment by apoorvaaaa5** [comment]
Yes will surely try going through it. Thank you for taking out the time and resolving the issue. Thank you.
