### ISSUE TITLE
Help with enabling debugger (gdb)

### ISSUE THREAD

**Issue by abhishekk06** [CMU-SAFARI/DAMOV#9]
Hi,

I am having a hard time debugging zsim. Attach debugger doesn't work for me. For some reason, it pops up a UI a bit too late (no clue why). Also, gdb doesn't show all the modules (especially filter array and etc). Any help is much appreciated.

**Comment by gearaldojunior** [comment]
Hi,

This thread might help you: https://github.com/s5z/zsim/issues/32
